version: '3.8'

services:

  rabbitmq:
    image: rabbitmq:3.12-management
    container_name: rabbitmq
    hostname: rabbitmq
    environment:
      RABBITMQ_DEFAULT_USER: admin
      RABBITMQ_DEFAULT_PASS: admin
    ports:
      - "5672:5672"  # Port AMQP pour les clients
      - "15672:15672" # Port de l'interface web
    volumes:
      - rabbitmq_data:/var/lib/rabbitmq
    networks:
      systeo-network:
        driver: bridge
  
  mongodb:
  image: mongo:6.0.12
  container_name: mongodb
  restart: always
  environment:
    MONGO_INITDB_ROOT_USERNAME: emna
    MONGO_INITDB_ROOT_PASSWORD: emna
    MONGO_INITDB_DATABASE: admin
  volumes:
    - mongodb_data:/data/db
  ports:
    - "27017:27017"
  networks:
    - systeo-network
  healthcheck:
    test: ["CMD", "mongosh", "--eval", "db.runCommand({ping:1})", "-u", "emna", "-p", "emna", "--authenticationDatabase", "admin"]
    interval: 10s
    timeout: 5s
    retries: 5

  eureka-server:
    image: emnasahnoun/eureka-server
    container_name: eureka-server
    hostname: eureka.systeo.tn
    ports:
      - "8761:8761"
    environment:
      - EUREKA_INSTANCE_HOSTNAME=eureka-server
      - EUREKA_CLIENT_SERVICE_URL_DEFAULTZONE=http://eureka-server:8761/eureka/
    networks:
      - systeo-network

  gateway-service:
    image: emnasahnoun/gateway-service
    container_name: gateway-service
    hostname: e1.systeo.tn
    ports:
      - "9091:9091"
 
    environment:
      - EUREKA_CLIENT_SERVICE_URL_DEFAULTZONE=http://eureka-server:8761/eureka/
    depends_on:
      - eureka-server
    networks:
      - systeo-network
  company-service:
    image: emnasahnoun/company-service
    container_name: company-service
    hostname: e2.systeo.tn
    ports:
      - "8073:8073"
    
    environment:
      - EUREKA_CLIENT_SERVICE_URL_DEFAULTZONE=http://eureka-server:8761/eureka/
      - SPRING_DATA_MONGODB_URI=mongodb://emna:emna@mongodb:27017/company?authSource=admin
    depends_on:
      - eureka-server
      mongodb:
        condition: service_healthy
    networks:
      - systeo-network
      
  project-service:
    image: emnasahnoun/project-service
    container_name: project-service
    hostname: e3.systeo.tn
    ports:
      - "8074:8074"
    
    environment:
      - EUREKA_CLIENT_SERVICE_URL_DEFAULTZONE=http://eureka-server:8761/eureka/
      - SPRING_DATA_MONGODB_URI=mongodb://emna:emna@mongodb:27017/project?authSource=admin
      - SPRING_RABBITMQ_HOST=rabbitmq
      - SPRING_RABBITMQ_PORT=5672
      - SPRING_RABBITMQ_USERNAME=admin
      - SPRING_RABBITMQ_PASSWORD=admin
    depends_on:
      - eureka-server
      mongodb:
        condition: service_healthy
      - rabbitmq
    networks:
      - systeo-network
      - rabbitmq

  commercial-service:
    image: emnasahnoun/commercial-service
    container_name: commercial-service
    hostname: e7.systeo.tn
    ports:
      - "8078:8078"
    
    environment:
      - EUREKA_CLIENT_SERVICE_URL_DEFAULTZONE=http://eureka-server:8761/eureka/
      - SPRING_DATA_MONGODB_URI=mongodb://emna:emna@mongodb:27017/commercial_documents?authSource=admin
    depends_on:
      - eureka-server
      mongodb:
        condition: service_healthy
    networks:
      - systeo-network

  activity-service:
    image: emnasahnoun/activity-service
    container_name: activity-service
    hostname: e4.systeo.tn
    ports:
      - "8075:8075"
    
    environment:
      - EUREKA_CLIENT_SERVICE_URL_DEFAULTZONE=http://eureka-server:8761/eureka/
      - SPRING_RABBITMQ_HOST=rabbitmq
      - SPRING_RABBITMQ_PORT=5672
      - SPRING_RABBITMQ_USERNAME=admin
      - SPRING_RABBITMQ_PASSWORD=admin
    depends_on:
      - eureka-server
      - rabbitmq
    networks:
      - systeo-network

  document-service:
    image: emnasahnoun/document-service
    container_name: document-service
    hostname: e6.systeo.tn
    ports:
      - "8077:8077"
    
    environment:
      - EUREKA_CLIENT_SERVICE_URL_DEFAULTZONE=http://eureka-server:8761/eureka/
      - SPRING_DATA_MONGODB_URI=mongodb://emna:emna@mongodb:27017/mediafile?authSource=admin
      - SPRING_RABBITMQ_HOST=rabbitmq
      - SPRING_RABBITMQ_PORT=5672
      - SPRING_RABBITMQ_USERNAME=admin
      - SPRING_RABBITMQ_PASSWORD=admin
    depends_on:
      - eureka-server
      mongodb:
        condition: service_healthy
      - rabbitmq
    networks:
      - systeo-network

  notification-service:
    image: emnasahnoun/notification-service
    container_name: notification-service
    hostname: e5.systeo.tn
    ports:
      - "8076:8076"
    
    environment:
      - EUREKA_CLIENT_SERVICE_URL_DEFAULTZONE=http://eureka-server:8761/eureka/
      - SPRING_RABBITMQ_HOST=rabbitmq
      - SPRING_RABBITMQ_PORT=5672
      - SPRING_RABBITMQ_USERNAME=admin
      - SPRING_RABBITMQ_PASSWORD=admin
    depends_on:
      - eureka-server
      - rabbitmq

    networks:
      - systeo-network

  email-service:
    image: emnasahnoun/email-service
    container_name: email-service
    hostname: e8.systeo.tn
    ports:
      - "8069:8069"
    
    environment:
      - EUREKA_CLIENT_SERVICE_URL_DEFAULTZONE=http://eureka-server:8761/eureka/
      - SPRING_RABBITMQ_HOST=rabbitmq
      - SPRING_RABBITMQ_PORT=5672
      - SPRING_RABBITMQ_USERNAME=admin
      - SPRING_RABBITMQ_PASSWORD=admin
    depends_on:
      - eureka-server
      - rabbitmq
    networks:
      - systeo-network
   
  angular-frontend:
    image: emnasahnoun/angular-frontend
    container_name: angular-frontend
    ports:
      - "4200:4200"
    
    depends_on:
      - gateway-service
    networks:
      - systeo-network

volumes:
  mongodb_data:
  rabbitmq_data:

networks:
  systeo-network:
    driver: bridge
