version: '3.8'

services:
  mongodb:
    image: mongo:6.0
    container_name: mongodb
    restart: always
    environment:
      MONGO_INITDB_ROOT_USERNAME: emna
      MONGO_INITDB_ROOT_PASSWORD: emna
    volumes:
      - mongodb_data:/data/db
    ports:
      - "27017:27017"
    networks:
      - systeo-network

  eureka-server:
    image: emnasahnoun/eureka-server
    container_name: eureka-server
    hostname: eureka.systeo.tn
    ports:
      - "8761:8761"
    environment:
      - EUREKA_INSTANCE_HOSTNAME=eureka-server
      - EUREKA_CLIENT_SERVICE_URL_DEFAULTZONE=http://eureka-server:8761/eureka/
    networks:
      - systeo-network

  gateway-service:
    image: emnasahnoun/gateway-service
    container_name: gateway-service
    hostname: e1.systeo.tn
    ports:
      - "9091:9091"
 
    environment:
      - EUREKA_CLIENT_SERVICE_URL_DEFAULTZONE=http://eureka-server:8761/eureka/
    depends_on:
      - eureka-server
    networks:
      - systeo-network
  company-service:
    image: emnasahnoun/company-service
    container_name: company-service
    hostname: e2.systeo.tn
    ports:
      - "8073:8073"
    
    environment:
      - EUREKA_CLIENT_SERVICE_URL_DEFAULTZONE=http://eureka-server:8761/eureka/
      - SPRING_DATA_MONGODB_URI=mongodb://emna:emna@mongodb:27017/company?authSource=admin
    depends_on:
      - eureka-server
      - mongodb
    networks:
      - systeo-network
      
  project-service:
    image: emnasahnoun/project-service
    container_name: project-service
    hostname: e3.systeo.tn
    ports:
      - "8074:8074"
    
    environment:
      - EUREKA_CLIENT_SERVICE_URL_DEFAULTZONE=http://eureka-server:8761/eureka/
      - SPRING_DATA_MONGODB_URI=mongodb://emna:emna@mongodb:27017/project?authSource=admin
    depends_on:
      - eureka-server
      - mongodb
    networks:
      - systeo-network

  commercial-service:
    image: emnasahnoun/commercial-service
    container_name: commercial-service
    hostname: e7.systeo.tn
    ports:
      - "8078:8078"
    
    environment:
      - EUREKA_CLIENT_SERVICE_URL_DEFAULTZONE=http://eureka-server:8761/eureka/
      - SPRING_DATA_MONGODB_URI=mongodb://emna:emna@mongodb:27017/commercial_documents?authSource=admin
    depends_on:
      - eureka-server
      - mongodb
    networks:
      - systeo-network

  activity-service:
    image: emnasahnoun/activity-service
    container_name: activity-service
    hostname: e4.systeo.tn
    ports:
      - "8075:8075"
    
    environment:
      - EUREKA_CLIENT_SERVICE_URL_DEFAULTZONE=http://eureka-server:8761/eureka/
    depends_on:
      - eureka-server
    networks:
      - systeo-network

  document-service:
    image: emnasahnoun/document-service
    container_name: document-service
    hostname: e6.systeo.tn
    ports:
      - "8077:8077"
    
    environment:
      - EUREKA_CLIENT_SERVICE_URL_DEFAULTZONE=http://eureka-server:8761/eureka/
      - SPRING_DATA_MONGODB_URI=mongodb://emna:emna@mongodb:27017/mediafile?authSource=admin
    depends_on:
      - eureka-server
      - mongodb
    networks:
      - systeo-network

  notification-service:
    image: emnasahnoun/notification-service
    container_name: notification-service
    hostname: e5.systeo.tn
    ports:
      - "8076:8076"
    
    environment:
      - EUREKA_CLIENT_SERVICE_URL_DEFAULTZONE=http://eureka-server:8761/eureka/
    depends_on:
      - eureka-server

    networks:
      - systeo-network

  email-service:
    image: emnasahnoun/email-service
    container_name: email-service
    hostname: e8.systeo.tn
    ports:
      - "8069:8069"
    
    environment:
      - EUREKA_CLIENT_SERVICE_URL_DEFAULTZONE=http://eureka-server:8761/eureka/
    depends_on:
      - eureka-server
    networks:
      - systeo-network
   
  angular-frontend:
    image: emnasahnoun/angular-frontend
    container_name: angular-frontend
    ports:
      - "4200:4200"
    
    depends_on:
      - gateway-service
    networks:
      - systeo-network

volumes:
  mongodb_data:

networks:
  systeo-network:
    driver: bridge
